#include <spine/Animation.c>
#include <spine/AnimationState.c>
#include <spine/AnimationStateData.c>
#include <spine/Array.c>
#include <spine/Atlas.c>
#include <spine/AtlasAttachmentLoader.c>
#include <spine/Attachment.c>
#include <spine/AttachmentLoader.c>
#include <spine/Bone.c>
#include <spine/BoneData.c>
#include <spine/BoundingBoxAttachment.c>
#include <spine/ClippingAttachment.c>
#include <spine/Color.c>
#include <spine/Event.c>
#include <spine/EventData.c>
#include <spine/extension.c>
#include <spine/IkConstraint.c>
#include <spine/IkConstraintData.c>
#include <spine/json.h>
#include <spine/json.c>
#include <spine/MeshAttachment.c>
#include <spine/PathAttachment.c>
#include <spine/PathConstraint.c>
#include <spine/PathConstraintData.c>
#include <spine/PointAttachment.c>
#include <spine/RegionAttachment.c>
#include <spine/Skeleton.c>
#include <spine/SkeletonBinary.c>
#include <spine/SkeletonBounds.c>
#include <spine/SkeletonClipping.c>
#include <spine/SkeletonData.c>
#include <spine/Skin.c>
#include <spine/Slot.c>
#include <spine/SlotData.c>
#include <spine/TransformConstraint.c>
#include <spine/TransformConstraintData.c>
#include <spine/Triangulator.c>
#include <spine/VertexAttachment.c>
#include <spine/VertexEffect.c>